[theme]
primaryColor = "#00c6ff"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#24243e"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
